### ISSUE TITLE
Homologação de inscrições

### ISSUE THREAD

**Issue by marciobarros** [unirio/dsw-spring#6]
Desenvolver uma página que apresenta uma tabela com uma linha para cada candidato inscrito no Edital selecionado pelo usuário. Para cada linha, a tabela deve ter as seguintes colunas:

* o nome do candidato

* um check-box indicando se sua inscrição foi homologada pela Comissão de Seleção. Somente os integrantes da Comissão de Seleção podem alterar o estado desta check-box;
  
* uma área de edição de texto com duas linhas para justificar a decisão tomada na check-box relacionada à homologação pela Comissão de Seleção;

* um check-box indicando se sua inscrição foi homologada pela Comissão de Recursos. Somente os integrantes da Comissão de Recursos podem alterar o estado desta check-box;
  
* uma área de edição de texto com duas linhas para justificar a decisão tomada na check-box relacionada à homologação pela Comissão de Recursos.
  
No início da homologação, todas as check-boxes devem estar no estado "incerto", ou seja, nem
ligadas, nem desligadas. Neste momento, todas as justificativas devem estar em branco. Deve 
haver um filtro que permita limitar a lista de candidatos apresentados de acordo com o seu 
nome, ou seja, somente os candidatos cujo nome contenha o texto digitado no filtro devem ser 
apresentados na tabela. Deve haver um segundo filtro que permita selecionar apenas os
candidatos que tenham sido homologados, não tenham sido homologados ou estejam incertos
com relação à check-box da Comissão de Seleção. Um terceiro filtro deve ser equivalente ao
segundo, mas considerando as check-boxes da Comissão de Recursos.

Sempre que um integrante da Comissão de Seleção mudar o estado da primeira check-box, o sistema deve salvar esta decisão no banco de dados, chamando uma ação para fazer isto. O mesmo deve ocorrer quando o usuário altera o texto da justificativa (tratar o evento de perda de foco da
área de texto). Os textos para justificativa devem estar presentes apenas quando a check-box
associada estiver desligada.

As mesmas ações valem para a Comissão de Recursos, que só deve alterar suas check-boxes e áreas de edição nos candidatos em que as check-boxes da Comissão de Seleção estiverem desligadas.

Este caso de uso deve ser acessado apenas por integrantes das comissões de seleção e recursos
do Edital selecionado. Além disso, o Edital deve estar no estado de homologação.

Valor: 3 pontos

**Comment by fariadavi** [comment]
Grupo 4

**Comment by marciobarros** [comment]
Caso de uso entregue e apresentado. Nota 9 para o código por conta dos seguintes problemas:

* duplo DROP e falta de comentários em diversas SP do banco de dados

* deveria usar uma variável local para simplificar o IF da SP antes mencionada

* falta de comentários nas SP

* falta de comentário em alguns métodos da classe Controller

**Comment by fariadavi** [comment]
Professor,

O duplo DROP IF EXISTS foi para "corrigir"o nome das SPs (homolAgacao -> homolOgacao) sem deixar lixo na base.

**Comment by marciobarros** [comment]
Entendido.
