### ISSUE TITLE
Dispensa de nota

### ISSUE THREAD

**Issue by marciobarros** [unirio/dsw-spring#7]
Analise a descrição do caso de uso "Homologação de inscrições". Implemente algo similar para
o controle de dispensa de notas. Este caso de uso deve ser acessado apenas por integrantes 
das comissões de seleção e recursos do Edital selecionado. Além disso, o Edital deve estar 
no estado de homologação.

Valor: 3 pontos

**Comment by fariadavi** [comment]
Grupo 4

**Comment by marciobarros** [comment]
Mesmos comentários do issue #7. Nota 9.
